'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const T = require('bamtigraph');
require('node:vm').runInThisContext(fs.readFileSync(path.join(__dirname, '../assets/demo-data.js'), 'utf8'));
const plain = options => new T.Chart({ fonts: { mode: 'bitmap' }, ...options });
const minimal = (values = [1, 2, 3], extra = {}) => plain({ series: [T.regularSeries('Value', values, 0, 300)], ...extra });
const near = (a, b, e = 1e-11) => assert.ok(Math.abs(a - b) <= e * Math.max(1, Math.abs(a), Math.abs(b)), `${a} != ${b}`);
const image = (w, h, values = [0, 0, 0, 255]) => ({ width: w, height: h, data: Uint8ClampedArray.from({ length: w * h * 4 }, (_, i) => values[i % 4]) });
test('Default configurations have independent ownership', () => { const a = T.defaults(), b = T.defaults(); const width = b.layout.width; a.layout.width = width + 1; assert.equal(b.layout.width, width); });
test('Timestamp conversions keep explicit units and offsets', () => { assert.equal(T.epoch('2026-09-08T12:00:00+09:00'), T.epoch('2026-09-08T03:00:00Z')); assert.equal(T.epoch(new Date(0)), 0); assert.equal(T.epoch('300.25'), 300.25); assert.equal(T.epoch(-.25), -.25); });
for (const v of ['2026-02-30T00:00:00Z', '2026-09-08T12:00:00', '2026-09-08', '2026-01-01T24:00:00Z', '2026-01-01T00:00:60Z', '2026-01-01T00:00:00+99:00', Infinity, new Date(NaN), '', 'not-a-time'])
    test('Reject invalid timestamp ' + String(v), () => assert.throws(() => T.epoch(v)));
test('Single-line text and timestamp ordering are validated', () => { assert.throws(() => T.series('bad\nname', [0], [1])); assert.throws(() => T.series('a', [1, 1], [1, 2])); assert.throws(() => T.series('a', [2, 1], [1, 2])); assert.throws(() => T.series('a', [0, 1], [1])); assert.throws(() => T.series('a', [0], [Infinity])); assert.throws(() => T.series('a', [0], ['1'])); });
test('Data arrays are copied and frozen', () => { const ts = [0, 300], vs = [1, 2], s = T.series('a', ts, vs); ts[0] = 100; vs[0] = 5; assert.equal(s.timestamps[0], 0); assert.equal(s.values[0], 1); assert.throws(() => { s.values[0] = 3; }); const c = plain({ series: [s] }); assert.ok(Object.isFrozen(c.config)); const updated = c.with({ title: 'B' }); assert.equal(c.config.title, ''); assert.equal(updated.config.title, 'B'); });
test('Typed numeric arrays and missing values normalize correctly', () => { const s = T.series('a', new Float64Array([0, 1, 2]), new Float64Array([1, NaN, 3])); assert.ok(Number.isNaN(s.values[1])); assert.ok(Number.isNaN(T.series('a', [0], [null]).values[0])); });
for (const [input, expected] of [['#0c0', [0, 204, 0, 255]], ['#0c08', [0, 204, 0, 136]], ['#0102ff', [1, 2, 255, 255]], ['#12345678', [18, 52, 86, 120]], ['transparent', [0, 0, 0, 0]], [[1, 2, 3], [1, 2, 3, 255]]])
    test('Color conversion ' + JSON.stringify(input), () => assert.deepEqual(T.color(input), expected));
for (const value of ['no', '#12345', '#ggg', [1, 2, 999], [-1, 2, 3], [1.5, 2, 3]])
    test('Invalid color rejected ' + JSON.stringify(value), () => assert.throws(() => T.color(value)));
test('Prototype pollution keys are rejected', () => { assert.throws(() => new T.Chart(JSON.parse('{"__proto__":{"polluted":true}}'))); assert.equal({}.polluted, undefined); });
for (const options of [{ layout: { width: 399 } }, { layout: { antialias: 0 } }, { layout: { pixelScale: 1.5 } }, { layout: { width: 8192, plotHeight: 4096, pixelScale: 8 } }, { yAxis: { minimum: 5, maximum: 5 } }, { yAxis: { base: 100 } }, { yAxis: { majorStep: 0 } }, { theme: { gridDash: [0, 2] } }, { fonts: { mode: 'unknown' } }, { timeAxis: { timezone: 'Invalid/Zone' } }, { timeAxis: { start: 5, end: 1 } }, { timeAxis: { ticks: [{ time: 2, label: 'A' }, { time: 1, label: 'B' }] } }])
    test('Reject invalid configuration ' + JSON.stringify(options), () => assert.throws(() => plain(options)));
test('Empty series require an explicit viewport', () => { assert.throws(() => plain({}).render()); const r = plain({ timeAxis: { start: 0, end: 3600 } }).render(); assert.equal(r.width, 595); assert.deepEqual(r.metadata.statistics, []); });
test('Singleton graph has a nonzero viewport without extrapolation', () => { const r = minimal([10]).render(); assert.deepEqual(r.metadata.timeRange, [-150, 150]); assert.equal(r.metadata.statistics[0].count, 1); });
test('Reference geometry and empty watermark are exact', () => { const r = DemoData.makeChart(T, false, { fonts: { mode: 'bitmap' } }).render(); assert.deepEqual(r.metadata.logicalSize, [595, 211]); assert.deepEqual(r.metadata.plotBox, [64, 34, 564, 156]); assert.equal(r.metadata.watermark, ''); assert.equal(r.data[3], 255); });
test('Current preserves final missingness; statistics use original samples', () => { const r = minimal([1, null, 3, NaN]).render(), s = r.metadata.statistics[0]; assert.equal(s.current, null); assert.equal(s.average, 2); assert.equal(s.maximum, 3); assert.equal(s.minimum, 1); assert.equal(s.count, 2); assert.equal(s.missing, 2); });
test('Viewport statistics are inclusive and not clipped to Y range', () => { const r = minimal([10, 20, 30, 40], { timeAxis: { start: 300, end: 600 }, yAxis: { minimum: 0, maximum: 10 } }).render(), s = r.metadata.statistics[0]; assert.equal(s.current, 30); near(s.average, 25); assert.equal(s.maximum, 30); assert.equal(s.count, 2); });
test('Legend override changes display but not observed statistics', () => { const s = T.regularSeries('A', [1, 2], 0, 300, { legendValues: { current: 99, average: 99, maximum: 99 } }); const r = plain({ series: [s] }).render(); assert.equal(r.metadata.statistics[0].current, 2); assert.equal(r.metadata.statistics[0].displayOverride.current, 99); });
test('Stable mean avoids overflow of finite identical large values', () => { const r = T.aggregate([0, 1], [1e308, 1e308], { interval: 300 }); assert.equal(r.values[0], 1e308); assert.throws(() => T.aggregate([0, 1], [1e308, 1e308], { method: 'sum' })); });
test('Display decimation does not change a spike maximum', () => { const n = 25000, values = Array.from({ length: n }, (_, i) => i === 12347 ? 999 : 10), s = T.regularSeries('A', values, 0, 1); const a = plain({ series: [s] }).render(), b = plain({ series: [s], layout: { width: 900 } }).render(); assert.equal(a.metadata.statistics[0].maximum, 999); assert.equal(a.metadata.statistics[0].count, n); assert.deepEqual(a.metadata.statistics, b.metadata.statistics); });
test('Explicit gaps do not become continuous lines', () => { const c = plain({ series: [T.series('A', [0, 300, 600], [5, NaN, 5], { color: '#ff0000' })], yAxis: { minimum: 0, maximum: 10, majorStep: 2 }, theme: { minorGrid: '#00000000', majorGrid: '#00000000' } }), r = c.render(), i = ((34 + 61) * r.width + (64 + 250)) * 4; assert.deepEqual(Array.from(r.data.slice(i, i + 3)), [255, 255, 255]); });
test('gapAfter stops lines even without explicit missing rows', () => { const r = plain({ series: [T.series('A', [0, 600], [5, 5], { gapAfter: 300 })], yAxis: { minimum: 0, maximum: 10 }, theme: { minorGrid: '#00000000', majorGrid: '#00000000' } }).render(), i = (95 * r.width + 314) * 4; assert.deepEqual(Array.from(r.data.slice(i, i + 3)), [255, 255, 255]); });
test('Step-post and linear paths differ while original statistics match', () => { const a = minimal([1, 9], { yAxis: { maximum: 10 } }), b = a.with({ series: a.config.series.map(s => ({ ...s, interpolation: 'step-post' })) }); const ra = a.render(), rb = b.render(); assert.deepEqual(ra.metadata.statistics, rb.metadata.statistics); assert.ok(T.compareImages(ra, rb).exactRatio < 1); });
test('Auto lower bound includes negative data', () => { const r = minimal([-10, 5, 12], { yAxis: { minimum: null } }).render(); assert.ok(r.metadata.yRange[0] < -10); assert.ok(r.metadata.yRange[1] > 12); });
test('IEC and custom unit scaling are explicit', () => { const r = minimal([1024, 2048, 3072], { yAxis: { base: 1024 } }).render(); assert.equal(r.metadata.yUnit.factor, 1024); assert.equal(r.metadata.yUnit.suffix, 'Ki'); const x = minimal([1, 2, 3], { yAxis: { scaleFactor: 1, suffix: '%' } }).render(); assert.equal(x.metadata.yUnit.suffix, '%'); });
test('Exact empty tick arrays disable time labels', () => { const r = minimal([1, 2, 3], { timeAxis: { ticks: [], minorTicks: [], majorTicks: [] } }).render(); assert.deepEqual(r.metadata.xLabels, []); });
test('Explicit tick positions and names are retained', () => { const r = minimal([1, 2, 3], { timeAxis: { ticks: [{ time: 300, label: 'MID' }], majorTicks: [300], minorTicks: [] } }).render(); assert.deepEqual(r.metadata.xLabels, [{ time: 300, label: 'MID', x: 314 }]); });
test('Tick density is guarded instead of hanging', () => assert.throws(() => minimal([1, 2], { timeAxis: { minorSeconds: .001 } }).render()));
test('Unsupported date directives are errors', () => assert.throws(() => T.formatTime(0, 'UTC', '%Q')));
test('Time labels use a fixed format and explicit zone', () => { assert.equal(T.formatTime(0, 'Asia/Seoul', '%F %T %z'), '1970-01-01 09:00:00 +0900'); assert.equal(T.formatTime(0, 'UTC', '%a %b %d %Y'), 'Thu Jan 01 1970'); assert.equal(T.formatTime(0, 'Asia/Kathmandu', '%H:%M'), '05:30'); assert.equal(T.formatTime(T.epoch('2026-01-01T00:00:00Z'), 'Asia/Kathmandu', '%H:%M'), '05:45'); });
test('DST spring gap does not synthesize nonexistent local 02:00', () => {
    const a = T.epoch('2024-03-10T05:00:00Z'), b = T.epoch('2024-03-10T10:00:00Z'), r = plain({ timeAxis: { start: a, end: b, mode: 'daily', timezone: 'America/New_York', labelSeconds: 3600, minorSeconds: 3600, majorSeconds: 3600 }, layout: { width: 1000 } }).render();
    assert.ok(!r.metadata.xLabels.some(t => t.label.startsWith('02:')));
    assert.ok(r.metadata.xLabels.some(t => t.label === '03:00'));
});
test('DST fall fold preserves both instants and disambiguates offsets', () => {
    const a = T.epoch('2024-11-03T04:00:00Z'), b = T.epoch('2024-11-03T09:00:00Z'), r = plain({ timeAxis: { start: a, end: b, mode: 'daily', timezone: 'America/New_York', labelSeconds: 3600, minorSeconds: 3600, majorSeconds: 3600 }, layout: { width: 1400 } }).render();
    const labels = r.metadata.xLabels.map(t => t.label);
    assert.ok(labels.includes('01:00 -0400'));
    assert.ok(labels.includes('01:00 -0500'));
});
test('Weekly labels are local noon for complete days only', () => { const a = T.epoch('2026-09-01T03:00:00Z'), b = a + 7 * 86400, r = plain({ timeAxis: { ...T.weekly('Asia/Seoul'), start: a, end: b } }).render(); assert.equal(r.metadata.xLabels.length, 6); for (const t of r.metadata.xLabels)
    assert.equal(T.formatTime(t.time, 'Asia/Seoul', '%H:%M'), '12:00'); });
test('Yearly labels use actual calendar month starts', () => { const r = plain({ timeAxis: { ...T.yearly('UTC'), start: T.epoch('2024-01-01T00:00:00Z'), end: T.epoch('2025-01-01T00:00:00Z') }, layout: { width: 1200 } }).render(); const feb = r.metadata.xLabels.find(t => t.label === 'Feb'); assert.ok(feb); assert.equal(T.formatTime(feb.time, 'UTC', '%F'), '2024-02-01'); });
test('Counter differences remain exact beyond 2^53', () => { const start = 2n ** 63n, r = T.counterRate([0, 2, 4], [start, start + 3n, start + 11n], { factor: 8 }); assert.ok(Number.isNaN(r.values[0])); assert.deepEqual(r.values.slice(1), [12, 32]); });
test('Unsafe Number counters are not silently rounded', () => assert.throws(() => T.counterRate([0, 1], [2 ** 63, 2 ** 63 + 100])));
test('Counter reset, missingness and explicit wrap policies', () => { const a = T.counterRate([0, 1, 2, 3, 4], [10, 20, null, 5, 6]); assert.equal(a.values[1], 10); assert.ok(Number.isNaN(a.values[2]) && Number.isNaN(a.values[3])); assert.equal(a.values[4], 1); const b = T.counterRate([0, 1], [255n, 2n], { onDecrease: 'wrap', counterBits: 8 }); assert.equal(b.values[1], 3); assert.ok(Number.isNaN(T.counterRate([0, 1], [20, 2]).values[1])); assert.throws(() => T.counterRate([0, 1], [20, 2], { onDecrease: 'wrap' })); });
test('128-bit counter and rate limits are enforced', () => { const m = 2n ** 128n - 1n; assert.equal(T.counterRate([0, 1], [m - 3n, m], { counterBits: 128 }).values[1], 3); assert.throws(() => T.counterRate([0], [m + 1n])); assert.ok(Number.isNaN(T.counterRate([0, 1], [0, 1000], { maxRate: 100 }).values[1])); });
for (const [method, expected] of [['mean', 3], ['min', 1], ['max', 5], ['sum', 9], ['last', 5]])
    test('Aggregation method ' + method, () => { const r = T.aggregate([0, 60, 120], [1, 3, 5], { interval: 300, method }); assert.deepEqual(r.timestamps, [0]); near(r.values[0], expected); });
test('Empty buckets remain missing and labels are left edges', () => { const r = T.aggregate([10, 610], [1, 3], { interval: 300 }); assert.deepEqual(r.timestamps, [0, 300, 600]); assert.ok(Number.isNaN(r.values[1])); });
test('Coverage and last-sample missingness are not fabricated', () => { const r = T.aggregate([0, 60], [1, 2], { interval: 300, expectedStep: 60, minCoverage: .8 }); assert.ok(Number.isNaN(r.values[0])); assert.ok(Number.isNaN(T.aggregate([0, 60], [1, null], { method: 'last' }).values[0])); });
test('Aggregation boundaries use half-open buckets and negative origins', () => { const r = T.aggregate([-300, 0, 300], [1, 2, 3], { interval: 300 }); assert.deepEqual(r.timestamps, [-300, 0, 300]); assert.deepEqual(r.values, [1, 2, 3]); assert.throws(() => T.aggregate([0, 1e8], [1, 2], { interval: 1, maxBuckets: 100 })); });
test('CSV handles BOM, quoted headers, CRLF, gaps and scientific notation', () => { const s = T.parseCSV('\ufeff"timestamp",inbound,outbound\r\n0,1e6,2\r\n300,,NaN\r\n'); assert.equal(s.length, 2); assert.equal(s[0].values[0], 1e6); assert.ok(Number.isNaN(s[1].values[1])); });
for (const csv of ['timestamp,inbound,inbound\n0,1,2', 'timestamp,inbound,outbound\n0,1', 'timestamp,inbound,outbound\n0,Infinity,2', 'timestamp,inbound,outbound\n0,"1,2', 'timestamp,inbound,outbound\n0,"1"x,2', 'timestamp,inbound,outbound\n0,1,2\n0,2,3', 'timestamp,inbound,outbound\n2026-01-01,1,2', 'timestamp,inbound,outbound\n0,0x10,2'])
    test('Reject malformed CSV ' + JSON.stringify(csv), () => assert.throws(() => T.parseCSV(csv)));
test('CSV limits and required headers are enforced', () => { assert.throws(() => T.parseCSV('timestamp,inbound,outbound\n0,1,2', { maxBytes: 4 })); assert.throws(() => T.parseCSV('timestamp,inbound,outbound\n0,1,2\n1,2,3', { maxRows: 1 })); assert.throws(() => T.parseCSV('time,inbound,outbound\n0,1,2')); });
test('CSV export aligns independent timestamps and protects header formulas', () => { const a = T.series('=danger', [0, 2], [1, 3]), b = T.series('Safe', [1], [2]), csv = T.toCSV([a, b]); assert.ok(csv.startsWith("timestamp,'=danger,Safe")); assert.ok(csv.includes('0,1,\r\n')); assert.ok(csv.includes('1,,2\r\n')); assert.throws(() => T.toCSV([a, a])); });
test('Nearest sample lookup respects independent timestamps and viewport', () => { const c = plain({ series: [T.series('A', [0, 200, 400], [1, 2, 3]), T.series('B', [100, 300], [10, 30])], timeAxis: { start: 100, end: 350 } }); const n = c.nearest(210); assert.equal(n[0].time, 200); assert.equal(n[1].time, 300); assert.equal(n[0].value, 2); });
test('Image comparison counts entire RGB pixels and ignores alpha', () => { const a = image(2, 2), b = image(2, 2); b.data[0] = 10; b.data[3] = 12; const d = T.compareImages(a, b, { tolerance: 10 }); assert.equal(d.exactRatio, .75); assert.equal(d.toleranceRatio, 1); assert.deepEqual(d.differenceBox, [0, 0, 1, 1]); near(d.meanAbsoluteError, 10 / 12); });
test('Image comparison cropping uses exclusive relative bounds', () => { const a = image(4, 4), b = image(4, 4); b.data[(2 * 4 + 2) * 4] = 7; const d = T.compareImages(a, b, { box: [1, 1, 4, 4] }); assert.deepEqual(d.differenceBox, [1, 1, 2, 2]); assert.throws(() => T.compareImages(a, image(3, 4))); assert.throws(() => T.compareImages(a, b, { box: [0, 0, 5, 4] })); });
test('Difference image amplifies RGB without changing input', () => { const a = image(1, 1), b = image(1, 1, [50, 20, 0, 255]), d = T.differenceImage(a, b, 4); assert.deepEqual(Array.from(d.data), [200, 80, 0, 255]); assert.equal(b.data[0], 50); });
test('Integer 2x expansion repeats every source channel exactly', () => { const c = minimal([5, 9, 3]), a = c.render(), b = c.with({ layout: { pixelScale: 2 } }).render(); for (let y = 0; y < b.height; y++)
    for (let x = 0; x < b.width; x++)
        for (let k = 0; k < 4; k++)
            assert.equal(b.data[(y * b.width + x) * 4 + k], a.data[(Math.floor(y / 2) * a.width + Math.floor(x / 2)) * 4 + k]); });
test('Bitmap output and PNG bytes are repeatable', () => { const c = minimal([3, 1, 8]), a = c.render(), b = c.render(); assert.equal(T.compareImages(a, b).exactRatio, 1); assert.deepEqual(a.toPNG(), b.toPNG()); });
test('System font mode fails clearly without Canvas rather than substituting', () => assert.throws(() => new T.Chart({ series: [T.series('A', [0], [1])] }).render(), /Canvas/));
test('Unsupported bitmap glyphs are rejected in strict mode', () => { assert.throws(() => minimal([1, 2], { title: '\uD55C\uAE00' }).render(), RangeError); });
test('Legend overflow is an error, never a truncated statistic', () => assert.throws(() => minimal([1, 2], { yAxis: { legendDecimals: 12 } }).render(), /Legend statistic/));
test('Dashboard dimensions, cropping and mixed scales', () => { const a = minimal([1, 2]), r = T.dashboard([{ chart: a, caption: 'A' }, { chart: a, caption: 'B' }]); assert.equal(r.width, 605); assert.equal(r.height, 451); const crop = T.dashboard([a, a], { cropHeight: 300 }); assert.equal(crop.height, 300); assert.throws(() => T.dashboard([a, a.with({ layout: { pixelScale: 2 } })])); assert.throws(() => T.dashboard([{ chart: a, caption: 'Too tall' }], { gap: 2 })); });
test('Golden RGBA digest is verified, not regenerated by tests', () => { const golden = JSON.parse(fs.readFileSync(path.join(__dirname, '../testdata/golden.json'), 'utf8')), r = DemoData.makeChart(T, false, { fonts: { mode: 'bitmap' }, timeAxis: T.daily('UTC') }).render(); const hash = crypto.createHash('sha256').update(r.data).digest('hex'); assert.equal(hash, golden.rgbaSHA256); assert.deepEqual([r.width, r.height], golden.imageSize); });
test('ES module and CommonJS packages render equivalent pixels', async () => { const m = await import('bamtigraph'); const a = minimal([1, 2, 3]).render(), b = new m.Chart({ fonts: { mode: 'bitmap' }, series: [m.regularSeries('Value', [1, 2, 3], 0, 300)] }).render(); assert.equal(T.compareImages(a, b).exactRatio, 1); });
test('Traffic wrapper does not silently turn invalid gap thresholds into zero', () => assert.throws(() => T.traffic([0, 1], [1, 2], [1, 2], { gapAfter: NaN })));
